spring:
  application:
    name: numbers-service

security:
  basic:
    enabled: false

---
spring:
    profiles: local

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
